# version: "3.8"

services:
  shell:
    build:
      context: .
      # dockerfile: apps/shell/dockerfile
      args:
        APP_NAME: shell
    container_name: shell
    ports:
      - "3001:80"

    networks:
      - superapp-network

networks:
  superapp-network:
    driver: bridge
